name: telegram message
on:
  release:
    types: [published]
jobs:
  build:
    name: Ğ¡Ğ±Ğ¾Ñ€ĞºĞ° Ğ¿Ñ€Ğ¾ĞµĞºÑ‚Ğ°
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
    - uses: actions/checkout@v3
    - name: Ğ£ÑÑ‚Ğ°Ğ½Ğ¾Ğ²ĞºĞ° Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM ÑƒÑÑ‚Ğ°Ğ½Ğ¾Ğ²ĞºĞ° Ğ¿Ğ°ĞºĞµÑ‚Ğ¾Ğ²
      run: |
        npm run inst

    - name: Ğ¡Ğ±Ğ¾Ñ€ĞºĞ° ĞºĞ¾Ğ¼Ğ¿Ğ¾Ğ½ĞµĞ½Ñ‚Ğ°
      run: |
        npm run build

    - name: Ğ—Ğ°Ğ³Ñ€ÑƒĞ·ĞºĞ° Ñ€ĞµĞ°Ğ»Ğ¸Ğ·Ğ° com_food Ğ´Ğ»Ñ Joomla CMS 3.x - 6.x
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: com_food-*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        disable_web_page_preview: false
        format: markdown
        message: |
          ğŸ‰ğŸ‰ğŸ‰ ĞĞ¾Ğ²Ñ‹Ğ¹ Ñ€ĞµĞ»Ğ¸Ğ·: ${{ github.event.release.name }} ğŸ‰ğŸ‰ğŸ‰

          [ĞŸĞ¾Ğ´Ñ€Ğ¾Ğ±Ğ½ĞµĞµ](https://github.com/ProjectSoft-STUDIONIONS/com_food/releases/tag/${{ github.ref_name }})
